config/routes.rb
Rails.application.routes.draw do
  resources :measurements
  devise_for :users
  resources :dashboard

  get 'home/index'

  root 'home#index'

end

app/models/measurement.rb
class Measurement < ActiveRecord::Base
  belongs_to :user

  validates :height, inclusion: { in: (1.1..3.0), message: "must be entered as a meter value" }
  validates :gender, inclusion: { in: %w(Male Female), message: "Male or female please"}
  validates :age, inclusion: { in: (18..120), message: "must be a full number between 18 and 120"}
  def bmi
  	bmi = (weight / (height*height)).round(2)
  end

  def req(weight,pal)
  	if gender == "Male"
	  	case age 
	  		when 10...18 then ((18.4*weight +581)*pal)
	  		when 18...30 then ((16.0*weight +545)*pal)
	  		when 30...60 then ((14.2*weight +593)*pal)
	  		when 60...70 then ((13.0*weight +567)*pal)
	  		when 70...120 then ((13.7*weight +481)*pal)
	  	end
  	elsif gender == "Female"
  		case age
  		  when 10...18 then ((11.1*weight +761)*pal)
  		  when 18...30 then ((13.1*weight +558)*pal)
  		  when 30...60 then ((9.74*weight +694)*pal)
  		  when 60...70 then ((10.2*weight +572)*pal)
  		  when 70...120 then ((10.0*weight +577)*pal)
  		end
    end
  end

   
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :measurements
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!

  def index
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  	if user_signed_in?
  		redirect_to :controller=>'dashboard', :action =>'index'
  	end
  end

end

app/controllers/measurements_controller.rb
class MeasurementsController < ApplicationController
  before_action :set_measurement, only: [:show, :edit, :update, :destroy]

  # GET /measurements
  # GET /measurements.json
  def index
    @measurements = Measurement.all
  end

  # GET /measurements/1
  # GET /measurements/1.json
  def show
  end

  # GET /measurements/new
  def new
    @measurement = current_user.measurements.build
  end

  # GET /measurements/1/edit
  def edit
  end

  # POST /measurements
  # POST /measurements.json
  def create
    @measurement = current_user.measurements.build(measurement_params)

    respond_to do |format|
      if @measurement.save
        format.html { redirect_to action: "index", notice: 'Measurement was successfully created.' }
        format.json { render :show, status: :created, location: @measurement }
      else
        format.html { render :new }
        format.json { render json: @measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /measurements/1
  # PATCH/PUT /measurements/1.json
  def update
    respond_to do |format|
      if @measurement.update(measurement_params)
        format.html { redirect_to action: "index", notice: 'Measurement was successfully updated.'}
        format.json { render :show, status: :ok, location: @measurement }
      else
        format.html { render :edit }
        format.json { render json: @measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /measurements/1
  # DELETE /measurements/1.json
  def destroy
    @measurement.destroy
    respond_to do |format|
      format.html { redirect_to measurements_url, notice: 'Measurement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_measurement
      @measurement = Measurement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def measurement_params
      params.require(:measurement).permit(:height, :weight, :pal, :gender, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/measurements_helper.rb
module MeasurementsHelper
end

app/views/dashboard/index.html.erb
<div class="container">
	<div class="panel"> 
	  <h1>Dashboard</h1>
		<p>Find me in app/views/dashboard/index.html.erb</p>

		<%= link_to "My Measurements", measurements_path, class: "btn btn-default" %>
	</div>
</div>

app/views/home/index.html.erb
<div class="container-fluid image-bg-fixed-height">

<p class="alert"><%= alert %></p>
<p class= "notice"><%= notice %></p>


<div class="container">
	<h1>Home</h1></br>
		<p>Welcome to Quantify Nutrition! The most accurate calculator for energy requirements on the web.</br></br>Quantify Nutrition is coded and run by a registered dietitian and as such you rest assured that every aspect of this free service is steeped in evidence-based science.</br></br>Knowledge is power, understand your body to better conquer it</p></br>
</div>


<div id="user-nav">
<% if user_signed_in? %>
<p> Hi <%= current_user.email %>. Not you? <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
  <% else %>
  <%= button_to('Sign in', new_user_session_path, :class => 'btn btn-large btn-primary') %> or <%= button_to('Register', new_user_registration_path, :class => 'btn btn-large btn-primary', :method => :get)  %>

<% end %>
</p>
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fatcamp5</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
  <link href='https://fonts.googleapis.com/css?family=Quicksand:300,400,700&subset=latin' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Josefin+Sans:400,400italic,700,700italic' rel='stylesheet' type='text/css'>

</head>

<body>


<%= yield %>


  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</div>
</body>
</html>

app/views/measurements/_form.html.erb
<div class="container">

<%= simple_form_for(@measurement) do |f| %>
  
  <% if @measurement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@measurement.errors.count, "error") %> prohibited this measurement from being saved:</h2>

      <ul>
      <% @measurement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :height,  label: "Height in meters", input_html: {step: '0.1', min: '0.1'}  %>
  <%= f.input :weight, label: "Weight in kilograms" %>
  <%= f.input :pal, input_html: {step: '0.1', min: '1.0'} %>
  <%= f.input :gender, collection: ["Male","Female"] %>
  <%= f.input :age %>
  <%= f.button :submit %>
<% end %>


</div>

app/views/measurements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Measurement</h1>

<table class="table">
  <thead>
    <tr>
      <th>Gender</th>
      <th>Age</th>
      <th>Height (m)</th>
      <th>Weight (kg)</th>
      <th>Pal</th>
      <th>BMI (kg/m<sup>2</sup>)</th>
      <th>Calorie Requirements (KCal)</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% current_user.measurements.each do |measurement| %>
      <tr>
        <td><%= measurement.gender %></td>
        <td><%= measurement.age %></td>
        <td><%= measurement.height %></td>
        <td><%= measurement.weight %></td>
        <td><%= measurement.pal %></td>
        <td><%= measurement.bmi %></td>
        <td><%= measurement.req(measurement.weight,measurement.pal) %></td>
        <% if measurement.user == current_user %>
        <td><%= link_to 'Edit', edit_measurement_path(measurement) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>


<br>
<% if current_user.measurements.count == 0 %>
  <%= link_to 'New Measurement', new_measurement_path, class: "btn btn-success" %>
<% else %>
  <%= link_to 'Edit Details', edit_measurement_path(Measurement.last), class: "btn btn-success" %>
<% end %>


<%= link_to 'Back', :back, class: "btn btn-success" %>

app/views/measurements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Height:</strong>
  <%= @measurement.height %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @measurement.weight %>
</p>

<p>
  <strong>Pal:</strong>
  <%= @measurement.pal %>
</p>

<p>
  <strong>BMI:</strong>
  <%= @measurement.bmi %>
</p>

<%= link_to 'Edit', edit_measurement_path(@measurement) %> |
<%= link_to 'Back', measurements_path %>